language: perl
os:
  - linux
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
before_install:
 - perlbrew install-cpanm -f
env:
 - AUTOMATED_TESTING=2
install:
  - cpanm --quiet DBI Text::CSV_XS SQL::Statement Pod::Parser Pod::Wordlist Pod::Escapes Text::Wrap Pod::Spell::CommonMistakes
